Changed subdirectory ps/ to doc/
git-svn-id: https://svn.code.sf.net/p/plob/code/trunk@658 9a56e421-9c0d-0410-8bba-bec7531eac79

diff --git a/plob/bin/plobimake b/plob/bin/plobimake
--- a/plob/bin/plobimake
+++ b/plob/bin/plobimake
@@ -188,20 +188,29 @@ esac
 echo "/* Junk C file generated by ${szScript} */
 #include	<plobimake.h>" > ${szTmpCfile}
 
+nFiles=''
 if [ -z "${szHeaderFile}" ]; then
   cat >> ${szTmpCfile}
+  nFiles='i'
 else
   for f in ${szHeaderFile}; do
     if [ -r "${f}" ]; then
+      nFiles="${nFiles}i"
       echo "#ifdef CurrentDirectory
 #undef CurrentDirectory
 #endif
 #define CurrentDirectory `( cd \`dirname ${f}\`; pwd; )`
 "'#include	"'"${f}"'"' >> ${szTmpCfile}
     else
-      echo "${szScript}: E02: Can't read file ${f}" 1>&2
+      echo "${szScript}: E02: Cannot read file ${f}" 1>&2
     fi
   done
+fi
+
+if [ -z "${nFiles}" ];then
+  rm -f ${szTmpCfile}
+  echo "${szScript}: E03: No input file(s) found" 1>&2
+  exit 1
 fi
 
 szCmdLine="${CPP}"
@@ -235,7 +244,7 @@ else
     case "`uname`" in
     *[cC][yY][gG][wW][iI][nN]*)
       fnTrimMakeFile "`basename ${szMakeFile}`" <${szTmpOutfile} >${TMP}/${nPID}_${szScript}.cr
-     dos2unix "${TMP}/${nPID}_${szScript}.cr" "${szMakeFile}";;
+      dos2unix "${TMP}/${nPID}_${szScript}.cr" "${szMakeFile}";;
     *)
       fnTrimMakeFile "`basename ${szMakeFile}`" <${szTmpOutfile} >${szMakeFile}
     esac
@@ -243,7 +252,7 @@ else
     nExitCode='1'
   fi
 fi
-rm -f ${TMP}/${nPID}_${szScript}.*
+# rm -f ${TMP}/${nPID}_${szScript}.*
 exit ${nExitCode}
 
 # Local variables:
